[project]
name = "cremalink-ha"
version = "v0.1.0b7"
description = "Cremalink for Home-Assistant Add-on & Integration"
requires-python = ">=3.13"
dependencies = [
    "homeassistant",
    "cremalink>=0.1.0b19, <1.0.0"
]
